version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "./nginx/conf.d:/etc/nginx/conf.d"
    networks:
      - backend
    depends_on:
    - estacionamento

  mongo:
    container_name: mongo
    image: tutum/mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      - AUTH=no
    volumes:
      - /data/db:/data/db
    networks:
      - backend

  estacionamento:
    image: haniel/estacionamento
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4000:4000"
    networks:
      - backend
    depends_on:
     - mongo

networks:
  backend:
    driver: bridge