version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    networks:
      - backend

  estacionamento:
    image: haniel/estacionamento
    container_name: app
    environment:
      - USER
      - PASSWORD
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4000:4000"
    networks:
      - backend
    depends_on:
     - mongodb

  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "./nginx/conf.d:/etc/nginx/conf.d"
    networks:
      - backend
    depends_on:
    - estacionamento

networks:
  backend:
    driver: bridge