version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    networks:
      - backend

  estacionamento_1:
    image: haniel/estacionamento
    container_name: estacionamento_1
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - backend
    depends_on:
     - mongodb

   estacionamento_2:
    image: haniel/estacionamento
    container_name: estacionamento_2
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - backend
    depends_on:
     - mongodb

   estacionamento_3:
    image: haniel/estacionamento
    container_name: estacionamento_3
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - backend
    depends_on:
     - mongodb    

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    - "4001:4001"
    - "4002:4002"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - backend
    depends_on:
    - estacionamento

networks:
  backend:
    driver: bridge